import { readFile } from "node:fs/promises";

import { captionManifest, captionModuleRef, captionTypes } from "@hypit/caption";
import { compositionDependency, compositionTypes } from "@hypit/composition";
import { mediaDependency, mediaTypes } from "@hypit/media";
import { programSpaceDependency, programSpaceTypes } from "@hypit/program-space";
import { narrativeDependency, narrativeTypes } from "@hypit/narrative";
import { semanticMapDependency, semanticMapTypes } from "@hypit/semantic-map";
import { svsRecipeType } from "@hypit/svs";
import type { ModuleManifest, ProducerRef } from "@hypit/protocol";

import { fineCaptionOneShotMotions } from "./recipe.js";

const previewImage = (file: string) => ({
  mediaType: "image/png",
  path: `preview/${file}`,
  open: async () => Uint8Array.from(await readFile(new URL(`../preview/${file}`, import.meta.url))),
});

export const captionFineModuleRef = { name: "@hypit/caption-fine", version: "1" } as const;
export const captionFineProducers = {
  render: { module: captionFineModuleRef, name: "render-fine-caption" },
} satisfies Record<string, ProducerRef>;

export const captionFineMarkupSurfaces = [
    {
      name: "style", tag: "Style", mode: "structured", outputs: [captionTypes.style],
      vocabulary: {
        summary: "Resolves one SVS Recipe and one exact font stack into a complete fine-grained Caption Style.",
        attributes: [
          { name: "id", kind: "identifier", required: true,
            summary: "Names this Style so a Caption Program can assign it." },
          { name: "recipe", kind: "reference", required: true, accepts: [svsRecipeType],
            summary: "Chooses the Recipe that carries Cue geometry, Paint and local motion.",
            recipe: [
              { name: "cue-min-words", required: true,
                summary: "Sets the fewest display Words the planner may leave in one Cue." },
              { name: "cue-max-words", required: true,
                summary: "Sets the most display Words one Cue may carry, which an indivisible Atom may still exceed." },
              { name: "stack-order", required: true,
                summary: "Places this Style's Cues in the Track's drawing order, low behind high." },
              { name: "x", required: true,
                summary: "Places the Cue box horizontally as a fraction of the Canvas width." },
              { name: "y", required: true,
                summary: "Places the Cue box vertically as a fraction of the Canvas height." },
              { name: "width", required: true,
                summary: "Sets the Cue box width as a fraction of the Canvas width." },
              { name: "anchor-x", required: false, values: ["left", "center", "right"], fallback: "left",
                summary: "Decides which horizontal edge of the Cue box sits on the placement point." },
              { name: "anchor-y", required: false, values: ["top", "center", "bottom"], fallback: "top",
                summary: "Decides which vertical edge of the Cue box sits on the placement point." },
              { name: "align", required: true, values: ["left", "center", "right"],
                summary: "Aligns the Words within each line of the Cue." },
              { name: "direction", required: false, values: ["ltr", "rtl"], fallback: "ltr",
                summary: "Sets the writing direction the Words are laid out in." },
              { name: "line-height", required: true,
                summary: "Sets the line box height as a multiple of the type size." },
              { name: "letter-spacing", required: false, fallback: "0",
                summary: "Adds pixels of tracking between glyphs." },
              { name: "word-gap", required: false, fallback: "a quarter of size",
                summary: "Sets the pixel gap between neighbouring Words." },
              { name: "size", required: true,
                summary: "Sets the type size in pixels." },
              { name: "text-transform", required: false, values: ["none", "uppercase", "lowercase"], fallback: "none",
                summary: "Recases every display Word before it is drawn." },
              { name: "fill", required: true,
                summary: "Paints the glyph body of an ordinary Word, as an RGB or RGBA hex color." },
              { name: "opacity", required: false, fallback: "1",
                summary: "Fades the whole glyph Paint of an ordinary Word." },
              { name: "gradient-from", required: false,
                summary: "Starts a glyph gradient that replaces the flat fill, and must be written together with gradient-to." },
              { name: "gradient-to", required: false,
                summary: "Ends the glyph gradient, and must be written together with gradient-from." },
              { name: "gradient-angle", required: false, fallback: "90",
                summary: "Turns the glyph gradient by this many degrees." },
              { name: "stroke-color", required: false, fallback: "#000000",
                summary: "Paints the outline drawn around each glyph." },
              { name: "stroke-width", required: false, fallback: "0",
                summary: "Sets the glyph outline thickness in pixels." },
              { name: "shadow-color", required: false, fallback: "#000000",
                summary: "Paints the soft drop shadow behind each glyph." },
              { name: "shadow-opacity", required: false, fallback: "0",
                summary: "Sets how strongly the glyph drop shadow reads." },
              { name: "shadow-x", required: false, fallback: "0",
                summary: "Offsets the glyph drop shadow horizontally in pixels." },
              { name: "shadow-y", required: false, fallback: "0",
                summary: "Offsets the glyph drop shadow vertically in pixels." },
              { name: "shadow-blur", required: false, fallback: "0",
                summary: "Softens the glyph drop shadow by this many pixels." },
              { name: "long-shadow-color", required: false, fallback: "#000000",
                summary: "Paints the solid extruded shadow trailing each glyph." },
              { name: "long-shadow-opacity", required: false, fallback: "0",
                summary: "Sets how strongly the extruded glyph shadow reads." },
              { name: "long-shadow-distance", required: false, fallback: "0",
                summary: "Sets how far the extruded glyph shadow travels in pixels." },
              { name: "long-shadow-angle", required: false, fallback: "45",
                summary: "Sets the direction the extruded glyph shadow travels in degrees." },
              { name: "glow-color", required: false, fallback: "#FFFFFF",
                summary: "Paints the halo bloomed around each glyph." },
              { name: "glow-opacity", required: false, fallback: "0",
                summary: "Sets how strongly the glyph halo reads." },
              { name: "glow-blur", required: false, fallback: "0",
                summary: "Spreads the glyph halo by this many pixels." },
              { name: "active-fill", required: false, fallback: "#FFD54A",
                summary: "Paints the glyph body of the Word being spoken." },
              { name: "active-opacity", required: false, fallback: "opacity",
                summary: "Fades the whole glyph Paint of the Word being spoken." },
              { name: "active-gradient-from", required: false,
                summary: "Starts the active glyph gradient, and must be written together with active-gradient-to." },
              { name: "active-gradient-to", required: false,
                summary: "Ends the active glyph gradient, and must be written together with active-gradient-from." },
              { name: "active-gradient-angle", required: false, fallback: "gradient-angle",
                summary: "Turns the active glyph gradient by this many degrees." },
              { name: "active-stroke-color", required: false, fallback: "stroke-color",
                summary: "Paints the outline around the Word being spoken." },
              { name: "active-stroke-width", required: false, fallback: "stroke-width",
                summary: "Sets the active glyph outline thickness in pixels." },
              { name: "active-shadow-color", required: false, fallback: "shadow-color",
                summary: "Paints the drop shadow behind the Word being spoken." },
              { name: "active-shadow-opacity", required: false, fallback: "shadow-opacity",
                summary: "Sets how strongly the active drop shadow reads." },
              { name: "active-shadow-x", required: false, fallback: "shadow-x",
                summary: "Offsets the active drop shadow horizontally in pixels." },
              { name: "active-shadow-y", required: false, fallback: "shadow-y",
                summary: "Offsets the active drop shadow vertically in pixels." },
              { name: "active-shadow-blur", required: false, fallback: "shadow-blur",
                summary: "Softens the active drop shadow by this many pixels." },
              { name: "active-long-shadow-color", required: false, fallback: "long-shadow-color",
                summary: "Paints the extruded shadow trailing the Word being spoken." },
              { name: "active-long-shadow-opacity", required: false, fallback: "long-shadow-opacity",
                summary: "Sets how strongly the active extruded shadow reads." },
              { name: "active-long-shadow-distance", required: false, fallback: "long-shadow-distance",
                summary: "Sets how far the active extruded shadow travels in pixels." },
              { name: "active-long-shadow-angle", required: false, fallback: "long-shadow-angle",
                summary: "Sets the direction the active extruded shadow travels in degrees." },
              { name: "active-glow-color", required: false, fallback: "glow-color",
                summary: "Paints the halo bloomed around the Word being spoken." },
              { name: "active-glow-opacity", required: false, fallback: "glow-opacity",
                summary: "Sets how strongly the active halo reads." },
              { name: "active-glow-blur", required: false, fallback: "glow-blur",
                summary: "Spreads the active halo by this many pixels." },
              { name: "background", required: true,
                summary: "Paints the Cue box behind the Words, as an RGB or RGBA hex color." },
              { name: "border-color", required: false, fallback: "#00000000",
                summary: "Paints the Cue box border." },
              { name: "border-width", required: false, fallback: "0",
                summary: "Sets the Cue box border thickness in pixels." },
              { name: "padding", required: true,
                summary: "Insets the Words from the Cue box edge, as one pixel number or a vertical and horizontal pair." },
              { name: "radius", required: true,
                summary: "Rounds the Cue box corners by this many pixels." },
              { name: "underline", required: false, values: ["off", "always"], fallback: "off",
                summary: "Decides whether every Word carries a rule beneath it." },
              { name: "underline-color", required: false, fallback: "fill",
                summary: "Paints the ordinary Word underline." },
              { name: "underline-thickness", required: false, fallback: "2",
                summary: "Sets the ordinary Word underline thickness in pixels." },
              { name: "underline-offset", required: false, fallback: "4",
                summary: "Drops the ordinary Word underline this many pixels below the baseline." },
              { name: "active-underline", required: false, values: ["off", "current", "trail"], fallback: "off",
                summary: "Decides whether the Word being spoken, or every Word up to it, carries a rule beneath it." },
              { name: "active-underline-color", required: false, fallback: "#FFD54A",
                summary: "Paints the active Word underline." },
              { name: "active-underline-thickness", required: false, fallback: "3",
                summary: "Sets the active Word underline thickness in pixels." },
              { name: "active-underline-offset", required: false, fallback: "4",
                summary: "Drops the active Word underline this many pixels below the baseline." },
              { name: "karaoke", required: false, values: ["off", "current", "trail"], fallback: "off",
                summary: "Decides whether the active Paint marks only the Word being spoken or every Word up to it." },
              { name: "karaoke-transition", required: false, values: ["step", "wipe"], fallback: "step",
                summary: "Decides whether the karaoke Paint snaps at the Word boundary or sweeps across the glyphs." },
              { name: "active-box", required: false, values: ["off", "current", "trail"], fallback: "off",
                summary: "Decides whether a highlight box sits behind the Word being spoken or behind every Word up to it." },
              { name: "active-box-continuity", required: false, values: ["isolated", "joined"], fallback: "isolated",
                summary: "Decides whether trailing highlight boxes stand apart or merge into one run." },
              { name: "active-box-background", required: false, fallback: "#FFD54A",
                summary: "Paints the highlight box behind the active Word." },
              { name: "active-box-border-color", required: false, fallback: "#00000000",
                summary: "Paints the highlight box border." },
              { name: "active-box-border-width", required: false, fallback: "0",
                summary: "Sets the highlight box border thickness in pixels." },
              { name: "active-box-padding", required: false, fallback: "0",
                summary: "Insets the Word from the highlight box edge, as one pixel number or a vertical and horizontal pair." },
              { name: "active-box-radius", required: false, fallback: "8",
                summary: "Rounds the highlight box corners by this many pixels." },
              { name: "active-box-enter", required: false, values: fineCaptionOneShotMotions, fallback: "none",
                summary: "Plays this motion as the highlight box arrives on a Word." },
              { name: "active-box-exit", required: false, values: fineCaptionOneShotMotions, fallback: "none",
                summary: "Plays this motion as the highlight box leaves a Word." },
              { name: "active-box-transition-frames", required: false, fallback: "0",
                summary: "Sets how many Frames the highlight box entrance and exit each run for." },
              { name: "cue-enter", required: false, values: fineCaptionOneShotMotions, fallback: "none",
                summary: "Plays this motion as a Cue arrives." },
              { name: "cue-enter-frames", required: false, fallback: "0",
                summary: "Sets how many Frames the Cue entrance runs for." },
              { name: "cue-exit", required: false, values: fineCaptionOneShotMotions, fallback: "none",
                summary: "Plays this motion as a Cue leaves." },
              { name: "cue-exit-frames", required: false, fallback: "0",
                summary: "Sets how many Frames the Cue exit runs for." },
              { name: "atom-enter", required: false, values: fineCaptionOneShotMotions, fallback: "none",
                summary: "Plays this motion as an Atom arrives within its Cue." },
              { name: "atom-enter-frames", required: false, fallback: "0",
                summary: "Sets how many Frames the Atom entrance runs for." },
              { name: "atom-exit", required: false, values: fineCaptionOneShotMotions, fallback: "none",
                summary: "Plays this motion as an Atom leaves within its Cue." },
              { name: "atom-exit-frames", required: false, fallback: "0",
                summary: "Sets how many Frames the Atom exit runs for." },
              { name: "atom-reveal", required: false, values: ["all", "on-start", "typewriter"], fallback: "all",
                summary: "Decides whether a Cue shows all of its Atoms at once or uncovers them as they are spoken." },
              { name: "active-response", required: false, values: fineCaptionOneShotMotions, fallback: "none",
                summary: "Plays this motion on a Word at the moment it becomes the spoken one." },
              { name: "active-response-frames", required: false, fallback: "6",
                summary: "Sets how many Frames the active response runs for." },
              { name: "active-scale", required: false, fallback: "1.08",
                summary: "Sets how far the active response grows the Word." },
              { name: "slide-distance", required: false, fallback: "24",
                summary: "Sets how far the sliding and wiping motions travel in pixels." },
              { name: "loop", required: false, fallback: "none",
                values: ["none", "shake", "wobble", "glow-pulse", "breathe", "float", "pulse", "flicker"],
                summary: "Plays this motion continuously for as long as its target is on screen." },
              { name: "loop-target", required: false, values: ["cue", "active-atom"], fallback: "cue",
                summary: "Decides whether the looping motion moves the whole Cue or only the Atom being spoken." },
              { name: "loop-period-frames", required: false, fallback: "12",
                summary: "Sets how many Frames one cycle of the looping motion takes." },
              { name: "loop-intensity", required: false, fallback: "1",
                summary: "Scales how far the looping motion carries." },
            ] },
          { name: "font", kind: "reference", required: true,
            accepts: [mediaTypes.fontArtifact, mediaTypes.fontStack],
            summary: "Chooses the primary face, or a whole reusable stack that already carries its own fallbacks." },
        ],
        children: [
          { tag: "Fallback", cardinality: "many",
            summary: "Appends one more exact face after the primary one, in the order written, and accepts no children of its own.",
            attributes: [
              { name: "font", kind: "reference", required: true, accepts: [mediaTypes.fontArtifact],
                summary: "Chooses the single face this fallback contributes." },
            ] },
        ],
        example: `<fonts:Stack id="caption-font" family="inter" weight="800" style="normal"/>
<caption-fine:Style id="primary-caption" recipe={studio.caption.primary} font={caption-font}/>`,
        notes: [
          "Referencing a font stack in `font` and writing `<Fallback>` children are both allowed; the stack's faces come first.",
          "The Style is addressed by its own id, and the element accepts no text.",
          "The Recipe accepts only the properties declared here; any other property is rejected.",
          "A gradient needs both of its colors: writing any one of `gradient-from`, `gradient-to` or `gradient-angle` without both colors is rejected, and the same holds for the `active-` gradient.",
          "The active glyph Paint inherits every base property it does not override, except the gradient, which the active Paint drops unless it writes its own.",
        ],
      },
    },
    {
      name: "track", tag: "Track", mode: "structured", outputs: [compositionTypes.visualTrack],
      vocabulary: {
        summary: "Joins a planned Caption against the measured SemanticMap and renders it as one ordinary peer VisualTrack.",
        appearance: "One block of caption text wrapped into lines inside a rounded Cue box, placed at a Recipe-chosen point on the Canvas and spanning a fraction of its width. Cues follow the speech one after another, each arriving and leaving with its own motion, and the Words of a Cue either stand there together from its first Frame or uncover as they are spoken. As the speech advances, the Word being spoken, or every Word up to it, is repainted in the active Paint, snapping at the Word boundary or sweeping across the glyphs, and it may take a rule beneath it, a rounded highlight capsule behind it and a brief pop at the moment it becomes the spoken one. That capsule either stands alone on each Atom or grows as one continuous run over everything already read, following the Words across line breaks.\n\nEvery Word of every Cue is drawn in one typeface, the one its Style names: emphasis varies by Word through the active Paint, never by typeface, and lines exist only where the text wraps, so a line cannot be given a face, colour or weight of its own. A caption whose lines are set in different typefaces is outside what this Track can draw.",
        preview: previewImage("Track.png"),
        attributes: [
          { name: "id", kind: "identifier", required: true,
            summary: "Names this Track so its rendered output can be placed in a Film." },
          { name: "display", kind: "reference", required: true, accepts: [narrativeTypes.captionDisplay],
            summary: "Chooses the display Atoms and Words the Cues are drawn from." },
          { name: "correspondence", kind: "reference", required: true, accepts: [narrativeTypes.captionCorrespondence],
            summary: "Chooses the link from display Words back to the spoken Script." },
          { name: "map", kind: "reference", required: true, accepts: [semanticMapTypes.complete],
            summary: "Chooses the measured Word windows that give every Cue its time." },
          { name: "program", kind: "reference", required: true, accepts: [captionTypes.program],
            summary: "Chooses the Style assignment that decides which Style each run is rendered in." },
          { name: "plan", kind: "reference", required: true, accepts: [captionTypes.plan],
            summary: "Chooses the Cue cuts the planner produced for this display." },
          { name: "space", kind: "reference", required: true, accepts: [programSpaceTypes.programSpace],
            summary: "Chooses the ProgramSpace the rendered Track is laid out against." },
        ],
        ports: [
          { name: "track", type: compositionTypes.visualTrack,
            summary: "The rendered Caption as one self-contained VisualTrack." },
        ],
        example: `<caption-fine:Track
  id="captions"
  display={story.caption}
  correspondence={story.caption.correspondence}
  map={timing.map}
  space={speech.space}
  program={caption-program}
  plan={caption-plan.plan}
/>`,
        notes: [
          "The element is empty; it accepts no children and no text.",
          "One Track renders the Program's default Style and every ordered replacement together.",
        ],
      },
    },
  ] as const;


export const captionFineManifest: ModuleManifest = {
  format: "hypit.module@1",
  name: captionFineModuleRef.name,
  version: captionFineModuleRef.version,
  dependencies: [
    { module: captionModuleRef },
    compositionDependency,
    mediaDependency,
    narrativeDependency,
    programSpaceDependency,
    semanticMapDependency,
  ],
  types: [],
  capabilities: [],
  producers: [{
    name: captionFineProducers.render.name,
    inputs: [
      { name: "caption", type: captionTypes.timedProjection },
      { name: "program", type: captionTypes.program },
      { name: "display", type: narrativeTypes.captionDisplay },
      { name: "space", type: programSpaceTypes.programSpace },
    ],
    outputs: [{ name: "track", type: compositionTypes.visualTrack }],
    needs: [],
  }],
};
