import { BuildMachine, buildDefinition, reduce } from "@narratage/core";
import type { BuildState } from "@narratage/protocol";
import { verifyRuntimeCoverage } from "./profile.js";
import type { RuntimeClosure } from "./profile.js";

import type {
  BuildScheduler,
  BuildSchedulerOptions,
  RuntimeCommandExecutor,
  RuntimeExecutionResult,
  RuntimeRunnableCommand,
  ScheduledBuild,
  ScheduledBuildResult,
  SchedulerExecutionOutcome,
} from "./types.js";

type MutableBuild = {
  readonly id: string;
  state: BuildState;
  machine: BuildMachine | undefined;
  readonly outcomes: SchedulerExecutionOutcome[];
  blocked: ScheduledBuildResult["blocked"];
  stopped: boolean;
};

type ActiveResult = {
  readonly key: string;
  readonly build: MutableBuild;
  readonly command: RuntimeRunnableCommand;
  readonly execution?: RuntimeExecutionResult;
  readonly error?: unknown;
};

type ActiveCommand = {
  readonly build: MutableBuild;
  readonly command: RuntimeRunnableCommand;
  readonly promise: Promise<ActiveResult>;
};

function positiveInteger(value: number, name: string): number {
  if (!Number.isSafeInteger(value) || value < 1) throw new Error(`${name} must be a positive safe integer`);
  return value;
}

function buildCommandKey(build: string, command: string): string {
  return `${build}\u0000${command}`;
}

/**
 * Queue-free, one-process reference Scheduler. It atomically admits every declared resource
 * across all submitted Builds,
 * but never searches a Graph: every runnable command is regenerated by Core through the Executor.
 */
export class LocalBuildScheduler implements BuildScheduler {
  readonly #executor: RuntimeCommandExecutor;
  readonly #maxConcurrency: number;
  readonly #resourceLimits: Readonly<Record<string, number>>;
  readonly #runtimeClosure: RuntimeClosure | undefined;
  readonly #buildStore: BuildSchedulerOptions["buildStore"];

  constructor(executor: RuntimeCommandExecutor, options: BuildSchedulerOptions = {}) {
    this.#executor = executor;
    this.#maxConcurrency = positiveInteger(options.maxConcurrency ?? 4, "maxConcurrency");
    this.#runtimeClosure = options.runtimeClosure === undefined
      ? undefined
      : structuredClone(options.runtimeClosure);
    this.#buildStore = options.buildStore;
    for (const [resource, limit] of Object.entries(options.resourceLimits ?? {})) {
      if (resource.trim().length === 0) throw new Error("resource override name must not be empty");
      positiveInteger(limit, `resource ${resource}`);
    }
    this.#resourceLimits = { ...(options.resourceLimits ?? {}) };
  }

  async run(requests: readonly ScheduledBuild[]): Promise<readonly ScheduledBuildResult[]> {
    const ids = new Set<string>();
    const builds: MutableBuild[] = [];
    for (const request of requests) {
      if (request.id.trim().length === 0) throw new Error("scheduled build id must not be empty");
      if (ids.has(request.id)) throw new Error(`scheduled build ${request.id} is duplicated`);
      ids.add(request.id);
      let state = structuredClone(request.state);
      let machine: BuildMachine | undefined;
      if (this.#buildStore !== undefined) {
        let snapshot = request.snapshot ?? await this.#buildStore.read(request.id);
        if (snapshot !== undefined && snapshot.build !== request.id) {
          throw new Error(`scheduled Build snapshot ${snapshot.build} does not belong to ${request.id}`);
        }
        if (snapshot === undefined) {
          try {
            snapshot = await this.#buildStore.create(request.id, buildDefinition(state));
          } catch (error) {
            snapshot = await this.#buildStore.read(request.id);
            if (snapshot === undefined) throw error;
          }
        }
        state = snapshot.state;
        machine = new BuildMachine(snapshot.definition, snapshot.facts);
      }
      if (this.#runtimeClosure !== undefined) verifyRuntimeCoverage(this.#runtimeClosure, state);
      builds.push({
        id: request.id,
        state,
        machine,
        outcomes: [],
        blocked: [],
        stopped: false,
      });
    }
    const active = new Map<string, ActiveCommand>();
    const resourceDefaults = new Map<string, number>();
    let cursor = 0;

    const resourceLimit = (resource: RuntimeRunnableCommand["resources"][number]): number => {
      const override = this.#resourceLimits[resource.id];
      if (override !== undefined) return override;
      const proposed = positiveInteger(resource.maxActive, `resource ${resource.id} default`);
      const previous = resourceDefaults.get(resource.id);
      if (previous !== undefined && previous !== proposed) {
        throw new Error(`resource ${resource.id} has conflicting default concurrency ${previous} and ${proposed}`);
      }
      resourceDefaults.set(resource.id, proposed);
      return proposed;
    };

    const accept = async (build: MutableBuild, event: import("@narratage/protocol").CommandResult): Promise<void> => {
      if (this.#buildStore === undefined || build.machine === undefined) {
        build.state = reduce(build.state, event);
        return;
      }
      const fact = build.machine.evaluate(event);
      if (fact === undefined) {
        build.state = build.machine.view();
        return;
      }
      await this.#buildStore.append(build.id, fact);
      build.machine.commit();
      build.state = build.machine.view();
    };

    const preparations = async (): Promise<Map<string, readonly RuntimeRunnableCommand[]>> => {
      const ready = new Map<string, readonly RuntimeRunnableCommand[]>();
      for (const build of builds) {
        if (build.stopped || build.state.status === "complete" || build.state.status === "failed") {
          ready.set(build.id, []);
          continue;
        }
        const prepared = this.#executor.prepare(build.state);
        build.state = prepared.state;
        build.blocked = prepared.blocked;
        ready.set(build.id, prepared.runnable.filter((item) =>
          !active.has(buildCommandKey(build.id, item.command.id))));
      }
      return ready;
    };

    const resourceCounts = (): Map<string, number> => {
      const counts = new Map<string, number>();
      for (const item of active.values()) {
        for (const resource of item.command.resources) {
          counts.set(resource.id, (counts.get(resource.id) ?? 0) + 1);
        }
      }
      return counts;
    };

    const launch = (build: MutableBuild, command: RuntimeRunnableCommand): void => {
      const key = buildCommandKey(build.id, command.command.id);
      const startedFrom = build.state;
      const promise = this.#executor.executeCommand(startedFrom, command, { build: build.id }).then(
        (execution) => ({ key, build, command, execution }),
        (error: unknown) => ({ key, build, command, error }),
      );
      active.set(key, { build, command, promise });
    };

    while (true) {
      const ready = await preparations();
      const counts = resourceCounts();
      let slots = this.#maxConcurrency - active.size;

      while (slots > 0 && builds.length > 0) {
        let selected = false;
        for (let offset = 0; offset < builds.length; offset += 1) {
          const index = (cursor + offset) % builds.length;
          const build = builds[index]!;
          const command = (ready.get(build.id) ?? []).find((candidate) =>
            candidate.resources.every((resource) =>
              (counts.get(resource.id) ?? 0) < resourceLimit(resource)));
          if (command === undefined) continue;
          ready.set(build.id, (ready.get(build.id) ?? []).filter((item) =>
            item.command.id !== command.command.id));
          launch(build, command);
          for (const resource of command.resources) {
            counts.set(resource.id, (counts.get(resource.id) ?? 0) + 1);
          }
          cursor = (index + 1) % builds.length;
          slots -= 1;
          selected = true;
          break;
        }
        if (!selected) break;
      }

      if (active.size === 0) break;
      const settled = await Promise.race([...active.values()].map((item) => item.promise));
      active.delete(settled.key);
      const build = settled.build;
      if (settled.execution === undefined) {
        build.stopped = true;
        build.outcomes.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          resources: settled.command.resources.map((resource) => resource.id),
          status: "error",
          message: settled.error instanceof Error ? settled.error.message : String(settled.error),
        });
        continue;
      }
      if (settled.execution.status === "pending") {
        build.stopped = true;
        build.outcomes.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          resources: settled.command.resources.map((resource) => resource.id),
          status: "pending",
          operation: settled.execution.operation,
          ...(settled.execution.wakeAt === undefined ? {} : { wakeAt: settled.execution.wakeAt }),
        });
        continue;
      }
      if (settled.execution.status === "deferred") {
        build.stopped = true;
        build.outcomes.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          resources: settled.command.resources.map((resource) => resource.id),
          status: "deferred",
          wakeAt: settled.execution.wakeAt,
          message: settled.execution.reason,
        });
        continue;
      }
      const event = settled.execution.event;
      try {
        await accept(build, event);
        build.outcomes.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          resources: settled.command.resources.map((resource) => resource.id),
          status: "completed",
        });
      } catch (error) {
        build.stopped = true;
        build.outcomes.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          resources: settled.command.resources.map((resource) => resource.id),
          status: "error",
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }

    return builds.map((build) => ({
      id: build.id,
      status: build.state.status === "complete"
        ? "complete"
        : build.state.status === "failed" ? "failed" : "paused",
      state: build.state,
      outcomes: [...build.outcomes],
      blocked: [...build.blocked],
    }));
  }
}
