import { reduce } from "@svml/core";
import type { BuildState } from "@svml/protocol";
import { verifyRuntimeClosure, verifyRuntimeCoverage } from "./profile.js";
import type { RuntimeClosure } from "./profile.js";

import type {
  LocalBuildSchedulerOptions,
  RuntimeCommandExecutor,
  RuntimeExecutionResult,
  RuntimeRunnableCommand,
  ScheduledBuild,
  ScheduledBuildResult,
  SchedulerJournalEntry,
} from "./types.js";

type MutableBuild = {
  readonly id: string;
  state: BuildState;
  revision: number | undefined;
  readonly journal: SchedulerJournalEntry[];
  blocked: ScheduledBuildResult["blocked"];
  stopped: boolean;
  completedEvents: number;
};

type ActiveResult = {
  readonly key: string;
  readonly build: MutableBuild;
  readonly command: RuntimeRunnableCommand;
  readonly execution?: RuntimeExecutionResult;
  readonly error?: unknown;
};

type ActiveCommand = {
  readonly build: MutableBuild;
  readonly command: RuntimeRunnableCommand;
  readonly promise: Promise<ActiveResult>;
};

function positiveInteger(value: number, name: string): number {
  if (!Number.isSafeInteger(value) || value < 1) throw new Error(`${name} must be a positive safe integer`);
  return value;
}

function buildCommandKey(build: string, command: string): string {
  return `${build}\u0000${command}`;
}

/**
 * Queue-free, one-process reference Scheduler. It shares lane limits across all submitted Builds,
 * but never searches a Graph: every runnable command is regenerated by Core through the Executor.
 */
export class LocalBuildScheduler {
  readonly #executor: RuntimeCommandExecutor;
  readonly #maxConcurrency: number;
  readonly #laneLimits: Readonly<Record<string, number>>;
  readonly #maxEventsPerBuild: number;
  readonly #runtimeClosure: RuntimeClosure | undefined;
  readonly #buildStore: LocalBuildSchedulerOptions["buildStore"];

  constructor(executor: RuntimeCommandExecutor, options: LocalBuildSchedulerOptions = {}) {
    this.#executor = executor;
    this.#maxConcurrency = positiveInteger(options.maxConcurrency ?? 4, "maxConcurrency");
    this.#maxEventsPerBuild = positiveInteger(options.maxEventsPerBuild ?? 1_000, "maxEventsPerBuild");
    this.#runtimeClosure = options.runtimeClosure === undefined
      ? undefined
      : structuredClone(options.runtimeClosure);
    this.#buildStore = options.buildStore;
    if (this.#runtimeClosure !== undefined) verifyRuntimeClosure(this.#runtimeClosure);
    for (const [lane, limit] of Object.entries(options.laneLimits ?? {})) {
      if (lane.trim().length === 0) throw new Error("lane override name must not be empty");
      positiveInteger(limit, `lane ${lane}`);
    }
    this.#laneLimits = { ...(options.laneLimits ?? {}) };
  }

  async run(requests: readonly ScheduledBuild[]): Promise<readonly ScheduledBuildResult[]> {
    const ids = new Set<string>();
    const builds: MutableBuild[] = [];
    for (const request of requests) {
      if (request.id.trim().length === 0) throw new Error("scheduled build id must not be empty");
      if (ids.has(request.id)) throw new Error(`scheduled build ${request.id} is duplicated`);
      ids.add(request.id);
      let state = structuredClone(request.state);
      let revision: number | undefined;
      if (this.#buildStore !== undefined) {
        let snapshot = await this.#buildStore.read(request.id);
        if (snapshot === undefined) {
          try {
            snapshot = await this.#buildStore.create(request.id, state);
          } catch (error) {
            snapshot = await this.#buildStore.read(request.id);
            if (snapshot === undefined) throw error;
          }
        }
        if (snapshot.state.id !== state.id) {
          throw new Error(`scheduled build ${request.id} already names a different Core Build`);
        }
        state = snapshot.state;
        revision = snapshot.revision;
      }
      if (this.#runtimeClosure !== undefined) verifyRuntimeCoverage(this.#runtimeClosure, state);
      builds.push({
        id: request.id,
        state,
        revision,
        journal: [],
        blocked: [],
        stopped: false,
        completedEvents: 0,
      });
    }
    const active = new Map<string, ActiveCommand>();
    const laneDefaults = new Map<string, number>();
    let cursor = 0;

    const laneLimit = (command: RuntimeRunnableCommand): number => {
      const override = this.#laneLimits[command.lane];
      if (override !== undefined) return override;
      const proposed = positiveInteger(command.maxConcurrency, `lane ${command.lane} default`);
      const previous = laneDefaults.get(command.lane);
      if (previous !== undefined && previous !== proposed) {
        throw new Error(`lane ${command.lane} has conflicting default concurrency ${previous} and ${proposed}`);
      }
      laneDefaults.set(command.lane, proposed);
      return proposed;
    };

    const persist = async (build: MutableBuild, state: BuildState): Promise<void> => {
      if (this.#buildStore === undefined) {
        build.state = state;
        return;
      }
      if (build.revision === undefined) throw new Error(`Build ${build.id} has no durable revision`);
      const written = await this.#buildStore.compareAndSwap(build.id, build.revision, state);
      if (written.status === "conflict") {
        build.state = written.current.state;
        build.revision = written.current.revision;
        throw new Error(`Build ${build.id} lost its authoritative Store revision`);
      }
      build.state = written.snapshot.state;
      build.revision = written.snapshot.revision;
    };

    const preparations = async (): Promise<Map<string, readonly RuntimeRunnableCommand[]>> => {
      const ready = new Map<string, readonly RuntimeRunnableCommand[]>();
      for (const build of builds) {
        if (build.stopped || build.state.status === "complete" || build.state.status === "failed") {
          ready.set(build.id, []);
          continue;
        }
        const prepared = this.#executor.prepare(build.state);
        if (prepared.state.status !== build.state.status) await persist(build, prepared.state);
        else build.state = prepared.state;
        build.blocked = prepared.blocked;
        ready.set(build.id, prepared.runnable.filter((item) =>
          !active.has(buildCommandKey(build.id, item.command.id))));
      }
      return ready;
    };

    const laneCounts = (): Map<string, number> => {
      const counts = new Map<string, number>();
      for (const item of active.values()) counts.set(item.command.lane, (counts.get(item.command.lane) ?? 0) + 1);
      return counts;
    };

    const launch = (build: MutableBuild, command: RuntimeRunnableCommand): void => {
      const key = buildCommandKey(build.id, command.command.id);
      const startedFrom = build.state;
      const promise = this.#executor.executeCommand(startedFrom, command.command.id, { build: build.id }).then(
        (execution) => ({ key, build, command, execution }),
        (error: unknown) => ({ key, build, command, error }),
      );
      active.set(key, { build, command, promise });
    };

    while (true) {
      const ready = await preparations();
      const counts = laneCounts();
      let slots = this.#maxConcurrency - active.size;

      while (slots > 0 && builds.length > 0) {
        let selected = false;
        for (let offset = 0; offset < builds.length; offset += 1) {
          const index = (cursor + offset) % builds.length;
          const build = builds[index]!;
          const command = (ready.get(build.id) ?? []).find((candidate) =>
            (counts.get(candidate.lane) ?? 0) < laneLimit(candidate));
          if (command === undefined) continue;
          ready.set(build.id, (ready.get(build.id) ?? []).filter((item) =>
            item.command.id !== command.command.id));
          launch(build, command);
          counts.set(command.lane, (counts.get(command.lane) ?? 0) + 1);
          cursor = (index + 1) % builds.length;
          slots -= 1;
          selected = true;
          break;
        }
        if (!selected) break;
      }

      if (active.size === 0) break;
      const settled = await Promise.race([...active.values()].map((item) => item.promise));
      active.delete(settled.key);
      const build = settled.build;
      if (settled.execution === undefined) {
        build.stopped = true;
        build.journal.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          lane: settled.command.lane,
          status: "error",
          message: settled.error instanceof Error ? settled.error.message : String(settled.error),
        });
        continue;
      }
      if (settled.execution.status === "pending") {
        build.stopped = true;
        build.journal.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          lane: settled.command.lane,
          status: "pending",
          operation: settled.execution.operation,
          ...(settled.execution.wakeAt === undefined ? {} : { wakeAt: settled.execution.wakeAt }),
        });
        continue;
      }
      const event = settled.execution.event;
      try {
        const next = reduce(build.state, event).state;
        await persist(build, next);
        build.completedEvents += 1;
        build.journal.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          lane: settled.command.lane,
          status: "completed",
          event: event.id,
        });
        if (build.completedEvents >= this.#maxEventsPerBuild
          && build.state.status !== "complete"
          && build.state.status !== "failed") {
          build.stopped = true;
          build.journal.push({
            command: settled.command.command.id,
            kind: settled.command.command.kind,
            lane: settled.command.lane,
            status: "error",
            message: `Build exceeded ${this.#maxEventsPerBuild} accepted events`,
          });
        }
      } catch (error) {
        build.stopped = true;
        build.journal.push({
          command: settled.command.command.id,
          kind: settled.command.command.kind,
          lane: settled.command.lane,
          status: "error",
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }

    return builds.map((build) => ({
      id: build.id,
      status: build.state.status === "complete"
        ? "complete"
        : build.state.status === "failed" ? "failed" : "paused",
      state: build.state,
      journal: [...build.journal],
      blocked: [...build.blocked],
    }));
  }
}
