export type {
  AlignedTranscriptEvidence,
  AlignedTranscriptSegment,
  AlignmentGroup,
  AlignmentRelation,
  CompleteSemanticMap,
  SemanticTimePoint,
  SpeechActivitySpan,
  SpeechAudioBasis,
  SpeechCharacterEvidence,
  SpeechWordEvidence,
  TimedSpeechSegment,
  TimedSpeechToken,
  TimingQuality,
} from "@narratage/video-contracts";
