import assert from "node:assert/strict";
import test from "node:test";
import { fixtureResource } from "../../../test/fixture-resource.js";

import {
  MemoryResourceStore,
  EndpointRegistry,
} from "@hypit/driver-node";
import type { EndpointRegistration } from "@hypit/driver-node";
import type { AsyncEndpoint } from "@hypit/endpoint-kit";
import { artifactTypes } from "@hypit/artifact";
import { backgroundRemovalCapabilities, backgroundRemovalRequest } from "@hypit/background-removal";
import { seedanceEndpoints, sealSeedanceRequest } from "@hypit/seedance";
import type { CanonicalValue, Need } from "@hypit/protocol";
import { createKieProvider } from "@hypit/provider-kie";

function need(constraints: CanonicalValue): Need {
  return {
    id: "need:kie-test",
    capability: seedanceEndpoints.mini!.capability,
    returns: seedanceEndpoints.mini!.returns,
    constraints,
    result: "record:kie-test",
  };
}

function removeBackgroundNeed(constraints: CanonicalValue): Need {
  return {
    id: "need:remove-background", capability: backgroundRemovalCapabilities.remove, returns: artifactTypes.blob,
    constraints, result: "record:remove-background",
  };
}

async function endpointFor(
  request: Need,
  fetch: typeof globalThis.fetch,
  now = () => 1_000,
): Promise<{ endpoint: AsyncEndpoint; registration: EndpointRegistration }> {
  const registry = new EndpointRegistry();
  const provider = createKieProvider({
    fetch,
    now,
    pollIntervalMs: 0,
    submissionIntervalMs: 0,
    requestTimeoutMs: 1_000,
    maxOperationMs: 60_000,
  });
  await provider.install(registry);
  const resolution = registry.resolve(request);
  assert.equal(resolution.status, "resolved");
  assert.equal(resolution.registration.kind, "asynchronous");
  return { endpoint: resolution.registration.endpoint, registration: resolution.registration };
}

function operation(_request: Need): string {
  return "operation:kie-test";
}

test("all KIE capabilities share one asynchronous task engine and use exact-model capacity", async () => {
  const provider = createKieProvider({
    fetch: async () => { throw new Error("no request expected"); },
    defaultConcurrency: 8,
    capabilityConcurrency: { "seedance-2-mini": 4 },
  });
  const registry = new EndpointRegistry();
  await provider.install(registry);
  const seed = need(sealSeedanceRequest("seedance-2-mini", {
    prompt: ["A clean studio shot."], resolution: ["720p"], aspectRatio: ["16:9"],
    duration: [5], generateAudio: [false], webSearch: [false],
  }) as unknown as CanonicalValue);
  const source = { kind: "blob" as const, resource: fixtureResource("lane-source"), size: 1, mediaType: "image/png" };
  const removal = removeBackgroundNeed(backgroundRemovalRequest(source) as unknown as CanonicalValue);
  const seedResolution = registry.resolve(seed);
  const removalResolution = registry.resolve(removal);
  assert.equal(seedResolution.status, "resolved");
  assert.equal(removalResolution.status, "resolved");
  assert.equal(seedResolution.registration.kind, "asynchronous");
  assert.equal(removalResolution.registration.kind, "asynchronous");
  assert.equal(seedResolution.registration.endpoint, removalResolution.registration.endpoint);
  assert.deepEqual(seedResolution.registration.scheduling, {
    resources: [
      { id: "pool:kie.default", limit: 8 },
      { id: "capacity:kie.default/seedance-2-mini", limit: 4 },
    ],
  });
});

test("KIE uploads referenced resources, polls one task, and persists generated bytes", async () => {
  const resources = new MemoryResourceStore();
  const firstFrame = await resources.put(new Uint8Array([1, 2, 3]), "image/png");
  const requestValue = sealSeedanceRequest("seedance-2-mini", {
    prompt: ["A presenter turns toward camera."],
    firstFrame: [{ role: "image", artifact: firstFrame }],
    resolution: ["720p"],
    aspectRatio: ["16:9"],
    duration: [6],
    generateAudio: [false],
    webSearch: [false],
  });
  const request = need(requestValue as unknown as CanonicalValue);
  const calls: string[] = [];
  const fakeFetch: typeof globalThis.fetch = async (input, init) => {
    const url = String(input);
    calls.push(url);
    if (url.endsWith("/api/file-stream-upload")) {
      assert.equal(init?.method, "POST");
      assert.match(String((init?.headers as Record<string, string>)["content-type"]), /^multipart\/form-data; boundary=/u);
      const chunks: Uint8Array[] = [];
      for await (const chunk of init?.body as unknown as AsyncIterable<Uint8Array>) chunks.push(chunk);
      const multipart = Buffer.concat(chunks).toString("latin1");
      assert.match(multipart, /name="fileName"\r\n\r\nres_[a-zA-Z0-9-]+\.png/u);
      assert.match(multipart, /name="uploadPath"\r\n\r\nhypit\/resources/u);
      assert.doesNotMatch(multipart, /svml\/resources/u);
      assert.ok(Buffer.concat(chunks).includes(Buffer.from([1, 2, 3])));
      return Response.json({
        success: true,
        code: 200,
        data: { downloadUrl: "https://tempfile.redpandaai.co/reference.png" },
      });
    }
    if (url.endsWith("/api/v1/jobs/createTask")) {
      const body = JSON.parse(String(init?.body)) as Record<string, unknown>;
      assert.equal(body.model, "bytedance/seedance-2-mini");
      const modelInput = body.input as Record<string, unknown>;
      assert.equal(modelInput.first_frame_url, "https://tempfile.redpandaai.co/reference.png");
      return Response.json({ code: 200, msg: "success", data: { taskId: "task_seedance_test" } });
    }
    if (url.includes("/api/v1/jobs/recordInfo")) {
      return Response.json({
        code: 200,
        data: {
          taskId: "task_seedance_test",
          model: "bytedance/seedance-2-mini",
          state: "success",
          resultJson: JSON.stringify({ resultUrls: ["https://tempfile.aiquickdraw.com/result.mp4"] }),
        },
      });
    }
    if (url.endsWith("/api/v1/common/download-url")) {
      return Response.json({ code: 200, data: "https://download.kie.test/result.mp4" });
    }
    if (url === "https://download.kie.test/result.mp4") {
      return new Response(new Uint8Array([9, 8, 7, 6]), {
        status: 200,
        headers: { "content-type": "video/mp4", "content-length": "4" },
      });
    }
    throw new Error(`Unexpected URL ${url}`);
  };
  const { endpoint } = await endpointFor(request, fakeFetch);
  const common = {
    command: { kind: "fulfill-need", id: "command:kie-test", need: request } as const,
    need: request,
    resources,
    credentials: { apiKey: { secret: "test-key" } },
    operation: operation(request),
  };
  const started = await endpoint.start(common);
  assert.equal(started.status, "pending");
  if (started.status !== "pending") return;
  assert.deepEqual(started.status === "pending" && started.progress, { phase: "submitted" });
  assert.equal(calls.length, 2);
  assert.equal(started.status === "pending" && (started.handle as Record<string, unknown>).taskId, "task_seedance_test");
  const completed = await endpoint.poll({
    ...common,
    handle: started.handle!,
  });
  assert.equal(completed.status, "completed");
  assert.equal(calls.length, 5);
  if (completed.status !== "completed") return;
  assert.equal(completed.result.value.kind, "inline");
  const result = completed.result.value.kind === "inline"
    ? completed.result.value.value as Record<string, unknown> : {};
  assert.equal("model" in result, false, "model choice belongs to the request graph");
  const videos = result.videos as Array<{ resource: string }>;
  assert.equal(videos.length, 1);
  assert.equal(await resources.has(videos[0]!.resource as `res_${string}`), true);
});

test("KIE fulfills generic Background Removal with the documented Recraft wire mapping", async () => {
  const resources = new MemoryResourceStore();
  const source = await resources.put(new Uint8Array([1, 2, 3, 4]), "image/png");
  const request = removeBackgroundNeed(backgroundRemovalRequest(source) as unknown as CanonicalValue);
  const calls: string[] = [];
  const fakeFetch: typeof globalThis.fetch = async (input, init) => {
    const url = String(input); calls.push(url);
    if (url.endsWith("/api/file-stream-upload")) {
      return Response.json({ code: 200, data: { downloadUrl: "https://tempfile.redpandaai.co/source.png" } });
    }
    if (url.endsWith("/api/v1/jobs/createTask")) {
      assert.deepEqual(JSON.parse(String(init?.body)), {
        model: "recraft/remove-background", input: { image: "https://tempfile.redpandaai.co/source.png" },
      });
      return Response.json({ code: 200, data: { taskId: "task_remove_background" } });
    }
    if (url.includes("/api/v1/jobs/recordInfo")) {
      return Response.json({ code: 200, data: {
        taskId: "task_remove_background", model: "recraft/remove-background", state: "success",
        resultJson: JSON.stringify({ resultUrls: ["https://tempfile.aiquickdraw.com/cutout.png"] }),
      } });
    }
    if (url.endsWith("/api/v1/common/download-url")) {
      return Response.json({ code: 200, data: "https://download.kie.test/cutout.png" });
    }
    if (url === "https://download.kie.test/cutout.png") {
      return new Response(new Uint8Array([9, 8, 7]), { status: 200, headers: { "content-type": "image/png" } });
    }
    throw new Error(`Unexpected URL ${url}`);
  };
  const { endpoint } = await endpointFor(request, fakeFetch);
  const common = {
    command: { kind: "fulfill-need", id: "command:remove-background", need: request } as const,
    need: request, resources, credentials: { apiKey: { secret: "test-key" } }, operation: operation(request),
  };
  const started = await endpoint.start(common);
  assert.equal(started.status, "pending");
  if (started.status !== "pending") return;
  const completed = await endpoint.poll({
    ...common, handle: started.handle!,
  });
  assert.equal(completed.status, "completed");
  if (completed.status !== "completed") return;
  assert.equal(completed.result.value.kind, "blob");
  assert.equal(completed.result.value.kind === "blob" && completed.result.value.mediaType, "image/png");
  assert.equal(calls.length, 5);
});

test("KIE keeps a timed-out task reserved while observing its actual remote end", async () => {
  const request = need({});
  let now = 0, unavailable = false, state = "generating", submissions = 0;
  const { endpoint } = await endpointFor(request, async (url) => {
    if (String(url).includes("createTask")) { submissions++; throw new Error("no submission expected"); }
    if (unavailable) throw new Error("offline");
    return Response.json({ code: 200, data: { state } });
  }, () => now);
  const common = { command: { kind: "fulfill-need", id: "need:test", need: request } as const,
    need: request, resources: new MemoryResourceStore(), credentials: { apiKey: { secret: "test" } }, operation: "op:test",
    handle: { taskId: "existing", routeKey: "seedance-2-mini", startedAt: 0 } };
  // Use the route's actual private handle format, obtained without any external call.
  const { kieRouteForCapability } = await import("../src/routes.js");
  common.handle.routeKey = kieRouteForCapability(request.capability)!.key;
  unavailable = true;
  assert.equal((await endpoint.poll(common)).status, "pending");
  now = 60_001;
  const timedOut = await endpoint.poll(common);
  assert.equal(timedOut.status, "pending");
  assert.equal(timedOut.status === "pending" && timedOut.failure?.code, "KIE_OPERATION_TIMEOUT");
  unavailable = false;
  assert.equal((await endpoint.poll({ ...common, settling: true })).status, "pending");
  state = "success";
  assert.deepEqual(await endpoint.poll({ ...common, settling: true }), { status: "settled" });
  assert.equal(submissions, 0);
});
