import assert from "node:assert/strict";
import test from "node:test";

import {
  MemoryArtifactStore,
  EndpointRegistry,
} from "@narratage/driver-node";
import type { EndpointRegistration } from "@narratage/driver-node";
import type { RecoverableEndpoint } from "@narratage/endpoint-kit";
import { artifactTypes } from "@narratage/artifact";
import { backgroundRemovalCapabilities, backgroundRemovalRequest } from "@narratage/background-removal";
import { seedanceEndpoints, sealSeedanceRequest } from "@narratage/seedance";
import { digestOf } from "@narratage/protocol";
import type { CanonicalValue, Need } from "@narratage/protocol";
import {
  createKieProvider,
  kieProviderImplementationDigest,
} from "@narratage/provider-kie";
import { sealOperationIdentity } from "@narratage/runtime";

function need(constraints: CanonicalValue): Need {
  return {
    id: "need:kie-test",
    capability: seedanceEndpoints.mini!.capability,
    returns: seedanceEndpoints.mini!.returns,
    constraints,
    requestedBy: "derivation:kie-test",
    result: "record:kie-test",
    accepts: "exact",
    conformanceFloor: "exact",
    requestDigest: digestOf({ capability: "seedance-mini", constraints }),
  };
}

function removeBackgroundNeed(constraints: CanonicalValue): Need {
  return {
    id: "need:remove-background", capability: backgroundRemovalCapabilities.remove, returns: artifactTypes.blob,
    constraints, requestedBy: "derivation:remove-background", result: "record:remove-background",
    accepts: "exact", conformanceFloor: "exact",
    requestDigest: digestOf({ capability: backgroundRemovalCapabilities.remove, constraints }),
  };
}

async function endpointFor(
  request: Need,
  fetch: typeof globalThis.fetch,
  now = () => 1_000,
): Promise<{ endpoint: RecoverableEndpoint; registration: EndpointRegistration }> {
  const registry = new EndpointRegistry();
  const provider = createKieProvider({
    fetch,
    fetchImplementationDigest: digestOf("provider-kie:test-fetch"),
    now,
    pollIntervalMs: 0,
    submissionIntervalMs: 0,
    requestTimeoutMs: 1_000,
    maxOperationMs: 60_000,
  });
  await provider.install(registry);
  const resolution = registry.resolve(request);
  assert.equal(resolution.status, "resolved");
  assert.equal(resolution.registration.kind, "recoverable");
  return { endpoint: resolution.registration.endpoint, registration: resolution.registration };
}

function operation(request: Need) {
  return sealOperationIdentity({
    build: "build:kie-test",
    command: "command:kie-test",
    endpoint: "kie.default",
    implementationDigest: kieProviderImplementationDigest,
    runtimeClosure: digestOf("runtime:kie-test"),
    requestDigest: request.requestDigest,
    attempt: 1,
  });
}

test("all KIE capabilities share one recoverable task engine and differ only by Route", async () => {
  const provider = createKieProvider({
    fetch: async () => { throw new Error("no request expected"); },
    fetchImplementationDigest: digestOf("provider-kie:route-registry-test"),
  });
  assert.equal(provider.bindings.length, 12);
  const registry = new EndpointRegistry();
  await provider.install(registry);
  const seed = need(sealSeedanceRequest("seedance-2-mini", {
    prompt: ["A clean studio shot."], resolution: ["720p"], aspectRatio: ["16:9"],
    duration: [5], generateAudio: [false], webSearch: [false],
  }) as unknown as CanonicalValue);
  const source = { kind: "blob" as const, digest: digestOf("route-source"), size: 1, mediaType: "image/png" };
  const removal = removeBackgroundNeed(backgroundRemovalRequest(source) as unknown as CanonicalValue);
  const seedResolution = registry.resolve(seed);
  const removalResolution = registry.resolve(removal);
  assert.equal(seedResolution.status, "resolved");
  assert.equal(removalResolution.status, "resolved");
  assert.equal(seedResolution.registration.kind, "recoverable");
  assert.equal(removalResolution.registration.kind, "recoverable");
  assert.equal(seedResolution.registration.endpoint, removalResolution.registration.endpoint);
});

test("KIE uploads content-addressed references, resumes one task, and persists generated bytes", async () => {
  const artifacts = new MemoryArtifactStore();
  const firstFrame = await artifacts.put(new Uint8Array([1, 2, 3]), "image/png");
  const requestValue = sealSeedanceRequest("seedance-2-mini", {
    prompt: ["A presenter turns toward camera."],
    firstFrame: [{ role: "image", artifact: firstFrame }],
    resolution: ["720p"],
    aspectRatio: ["16:9"],
    duration: [6],
    generateAudio: [false],
    webSearch: [false],
  });
  const request = need(requestValue as unknown as CanonicalValue);
  const calls: string[] = [];
  const fakeFetch: typeof globalThis.fetch = async (input, init) => {
    const url = String(input);
    calls.push(url);
    if (url.endsWith("/api/file-stream-upload")) {
      assert.equal(init?.method, "POST");
      assert.match(String((init?.headers as Record<string, string>)["content-type"]), /^multipart\/form-data; boundary=/u);
      const chunks: Uint8Array[] = [];
      for await (const chunk of init?.body as unknown as AsyncIterable<Uint8Array>) chunks.push(chunk);
      const multipart = Buffer.concat(chunks).toString("latin1");
      assert.match(multipart, /name="fileName"\r\n\r\n[0-9a-f]{64}\.png/u);
      assert.ok(Buffer.concat(chunks).includes(Buffer.from([1, 2, 3])));
      return Response.json({
        success: true,
        code: 200,
        data: { downloadUrl: "https://tempfile.redpandaai.co/reference.png" },
      });
    }
    if (url.endsWith("/api/v1/jobs/createTask")) {
      const body = JSON.parse(String(init?.body)) as Record<string, unknown>;
      assert.equal(body.model, "bytedance/seedance-2-mini");
      const modelInput = body.input as Record<string, unknown>;
      assert.equal(modelInput.first_frame_url, "https://tempfile.redpandaai.co/reference.png");
      return Response.json({ code: 200, msg: "success", data: { taskId: "task_seedance_test" } });
    }
    if (url.includes("/api/v1/jobs/recordInfo")) {
      return Response.json({
        code: 200,
        data: {
          taskId: "task_seedance_test",
          model: "bytedance/seedance-2-mini",
          state: "success",
          resultJson: JSON.stringify({ resultUrls: ["https://tempfile.aiquickdraw.com/result.mp4"] }),
        },
      });
    }
    if (url.endsWith("/api/v1/common/download-url")) {
      return Response.json({ code: 200, data: "https://download.kie.test/result.mp4" });
    }
    if (url === "https://download.kie.test/result.mp4") {
      return new Response(new Uint8Array([9, 8, 7, 6]), {
        status: 200,
        headers: { "content-type": "video/mp4", "content-length": "4" },
      });
    }
    throw new Error(`Unexpected URL ${url}`);
  };
  const { endpoint } = await endpointFor(request, fakeFetch);
  const common = {
    command: { kind: "fulfill-need", id: "command:kie-test", need: request } as const,
    need: request,
    artifacts,
    credentials: { apiKey: { secret: "test-key" } },
    operation: operation(request),
  };
  const started = await endpoint.start(common);
  assert.equal(started.status, "pending");
  assert.deepEqual(started.status === "pending" && started.progress, { phase: "submitted" });
  assert.equal(calls.length, 2);
  assert.equal(started.status === "pending" && (started.checkpoint as Record<string, unknown>).taskId, "task_seedance_test");
  const completed = await endpoint.resume({
    ...common,
    checkpoint: started.status === "pending" ? started.checkpoint : undefined,
  });
  assert.equal(completed.status, "completed");
  assert.equal(calls.length, 5);
  if (completed.status !== "completed") return;
  assert.equal(completed.result.value.kind, "inline");
  const result = completed.result.value.kind === "inline"
    ? completed.result.value.value as Record<string, unknown> : {};
  assert.equal(result.contract, "svml.generated-video-set@1");
  assert.equal("model" in result, false, "model choice belongs to the request graph and Receipt");
  assert.equal("requestDigest" in result, false, "request lineage belongs to the Need Receipt, not generated media");
  const videos = result.videos as Array<{ digest: string }>;
  assert.equal(videos.length, 1);
  assert.equal(await artifacts.has(videos[0]!.digest as `sha256:${string}`), true);
});

test("KIE never retries an ambiguous paid submission", async () => {
  const requestValue = sealSeedanceRequest("seedance-2-mini", {
    prompt: ["A clean studio shot."],
    resolution: ["720p"],
    aspectRatio: ["16:9"],
    duration: [5],
    generateAudio: [false],
    webSearch: [false],
  });
  const request = need(requestValue as unknown as CanonicalValue);
  let calls = 0;
  const { endpoint } = await endpointFor(request, async () => {
    calls += 1;
    throw new TypeError("socket closed after write");
  });
  const outcome = await endpoint.start({
    command: { kind: "fulfill-need", id: "command:kie-test", need: request },
    need: request,
    artifacts: new MemoryArtifactStore(),
    credentials: { apiKey: { secret: "test-key" } },
    operation: operation(request),
  });
  assert.equal(calls, 1);
  assert.equal(outcome.status, "failed");
  if (outcome.status !== "failed") return;
  assert.equal(outcome.failure.code, "KIE_SUBMISSION_OUTCOME_UNKNOWN");
  assert.equal(outcome.failure.retryable, false);
});

test("KIE preserves an HTTP-200 business rejection without calling it an ambiguous submission", async () => {
  const requestValue = sealSeedanceRequest("seedance-2-mini", {
    prompt: ["A clean studio shot."],
    resolution: ["720p"],
    aspectRatio: ["16:9"],
    duration: [5],
    generateAudio: [false],
    webSearch: [false],
  });
  const request = need(requestValue as unknown as CanonicalValue);
  let calls = 0;
  const { endpoint } = await endpointFor(request, async () => {
    calls += 1;
    return Response.json({ code: 422, msg: "aspect_ratio is required", data: null });
  });
  const outcome = await endpoint.start({
    command: { kind: "fulfill-need", id: "command:kie-test", need: request },
    need: request,
    artifacts: new MemoryArtifactStore(),
    credentials: { apiKey: { secret: "test-key" } },
    operation: operation(request),
  });
  assert.equal(calls, 1);
  assert.equal(outcome.status, "failed");
  if (outcome.status !== "failed") return;
  assert.equal(outcome.failure.code, "KIE_SUBMISSION_REJECTED");
  assert.match(outcome.failure.message, /aspect_ratio is required.*422/u);
  assert.equal(outcome.failure.retryable, false);
});

test("KIE refuses to resubmit when a recovered Operation has no task checkpoint", async () => {
  const requestValue = sealSeedanceRequest("seedance-2-mini", {
    prompt: ["A clean studio shot."],
    resolution: ["720p"],
    aspectRatio: ["16:9"],
    duration: [5],
    generateAudio: [false],
    webSearch: [false],
  });
  const request = need(requestValue as unknown as CanonicalValue);
  let calls = 0;
  const { endpoint } = await endpointFor(request, async () => {
    calls += 1;
    throw new Error("must not fetch");
  });
  const outcome = await endpoint.resume({
    command: { kind: "fulfill-need", id: "command:kie-test", need: request },
    need: request,
    artifacts: new MemoryArtifactStore(),
    credentials: { apiKey: { secret: "test-key" } },
    operation: operation(request),
    checkpoint: undefined,
  });
  assert.equal(calls, 0);
  assert.equal(outcome.status, "failed");
  if (outcome.status !== "failed") return;
  assert.equal(outcome.failure.code, "KIE_SUBMISSION_CHECKPOINT_MISSING");
  assert.equal(outcome.failure.retryable, false);
});

test("KIE fulfills generic Background Removal with the documented Recraft wire contract", async () => {
  const artifacts = new MemoryArtifactStore();
  const source = await artifacts.put(new Uint8Array([1, 2, 3, 4]), "image/png");
  const request = removeBackgroundNeed(backgroundRemovalRequest(source) as unknown as CanonicalValue);
  const calls: string[] = [];
  const fakeFetch: typeof globalThis.fetch = async (input, init) => {
    const url = String(input); calls.push(url);
    if (url.endsWith("/api/file-stream-upload")) {
      return Response.json({ code: 200, data: { downloadUrl: "https://tempfile.redpandaai.co/source.png" } });
    }
    if (url.endsWith("/api/v1/jobs/createTask")) {
      assert.deepEqual(JSON.parse(String(init?.body)), {
        model: "recraft/remove-background", input: { image: "https://tempfile.redpandaai.co/source.png" },
      });
      return Response.json({ code: 200, data: { taskId: "task_remove_background" } });
    }
    if (url.includes("/api/v1/jobs/recordInfo")) {
      return Response.json({ code: 200, data: {
        taskId: "task_remove_background", model: "recraft/remove-background", state: "success",
        resultJson: JSON.stringify({ resultUrls: ["https://tempfile.aiquickdraw.com/cutout.png"] }),
      } });
    }
    if (url.endsWith("/api/v1/common/download-url")) {
      return Response.json({ code: 200, data: "https://download.kie.test/cutout.png" });
    }
    if (url === "https://download.kie.test/cutout.png") {
      return new Response(new Uint8Array([9, 8, 7]), { status: 200, headers: { "content-type": "image/png" } });
    }
    throw new Error(`Unexpected URL ${url}`);
  };
  const { endpoint } = await endpointFor(request, fakeFetch);
  const common = {
    command: { kind: "fulfill-need", id: "command:remove-background", need: request } as const,
    need: request, artifacts, credentials: { apiKey: { secret: "test-key" } }, operation: operation(request),
  };
  const started = await endpoint.start(common);
  assert.equal(started.status, "pending");
  const completed = await endpoint.resume({
    ...common, checkpoint: started.status === "pending" ? started.checkpoint : undefined,
  });
  assert.equal(completed.status, "completed");
  if (completed.status !== "completed") return;
  assert.equal(completed.result.value.kind, "blob");
  assert.equal(completed.result.value.kind === "blob" && completed.result.value.mediaType, "image/png");
  assert.equal(calls.length, 5);
});
